services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      APP_ENV: dev
    volumes:
      - .:/var/www/html:cached
      - symfony_cache:/var/www/html/var/cache
      - symfony_logs:/var/www/html/var/log
      - symfony_vendor:/var/www/html/vendor
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name: symfony-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    working_dir: /var/www/html
    volumes:
      - symfony_code:/var/www/html:cached
    command: [ "npm", "run", "watch" ]
    depends_on:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - db
volumes:
  db_data:
  symfony_code:
  symfony_cache:
  symfony_logs:
  symfony_vendor:
